spring:
  application:
    name: betapp-naming-server
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: ${betapp-naming-server.port:8761}